DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS games CASCADE;
DROP TABLE IF EXISTS modes CASCADE;
DROP TABLE IF EXISTS highscores CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE games (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  rating INTEGER
);

CREATE TABLE modes (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT
);

CREATE TABLE highscores (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL,
  game_id INTEGER NOT NULL,
  mode_id INTEGER NOT NULL,
  score INTEGER NOT NULL
);
